export const manageUserDataModel = {
    name: '',
    emailAddress: '',
    address: '',
    tempPassword: '',
    mobileNumber: '',
    role: '',
    accountBusinessName: '',
    secondary_user_id: '',
    primary_user_id: '',
    id: ''
};
export const businessAccountDataModel = {
    id: '',
    businessName: '',
    phoneNumber: '',
    email: '',
    billingAddress: '',
    city: '',
    district: '',
    state: '',
    pinCode: '',
    gstNumber: '',
    gstUser: '',
    panNumber: '',
    businessType: '',
    industryType: '',
    businessRegistrationType: '',
    logo: '',
    signature: '',
}